### PR TITLE
Fix weird pixel jump on first tab

### PR DESCRIPTION
**Pull request by henrikdahl**

### CODE REVIEW

**Comment by henrikdahl** [comment]
Worth mentioning that it more or less makes this code redundant
```
.tabs_nav .tab_tab:first-of-type {
  border-left-color: transparent !important;
}
```

**Comment by rafaelrinaldi** [comment]
@henrikdahl Thanks man! I ended up solving this issue using a different approach (fb07510725e480f0d6b2c3c58c8af78e791c9388).

**Comment by henrikdahl** [comment]
@rafaelrinaldi Just thought I'd let you know that your approach won't work.

It now jumps the title 1px instead. It also leaves a transparent 1px border because of how it's rendered in browsers.

Not sure what about my approach you didn't like considering that's the foolproof solution ✌️

**Comment by rafaelrinaldi** [comment]
@henrikdahl Dang it, that's true! Nothing wrong with your implementation by the way, I was just messing around with the code in a local copy and thought the issue was fixed already. Will revert it and use your solution 👍

**Pull request closed without merging**
